-- Level 2 reuses the books dataset from Level 1.
-- This seed re-creates it idempotently so users who jump straight to L2 still have data.
DROP TABLE IF EXISTS books CASCADE;

CREATE TABLE books (
  id        SERIAL PRIMARY KEY,
  title     TEXT NOT NULL,
  author    TEXT NOT NULL,
  year      INT,
  pages     INT,
  rating    NUMERIC(3,1),
  genre     TEXT
);

INSERT INTO books (title, author, year, pages, rating, genre) VALUES
  ('The Great Gatsby',                     'F. Scott Fitzgerald', 1925, 180, 3.9, 'Classic'),
  ('1984',                                  'George Orwell',       1949, 328, 4.2, 'Dystopian'),
  ('To Kill a Mockingbird',                 'Harper Lee',          1960, 281, 4.3, 'Classic'),
  ('Brave New World',                       'Aldous Huxley',       1932, 311, 3.9, 'Dystopian'),
  ('The Catcher in the Rye',                'J.D. Salinger',       1951, 277, 3.8, 'Classic'),
  ('Pride and Prejudice',                   'Jane Austen',         1813, 432, 4.3, 'Romance'),
  ('The Hobbit',                            'J.R.R. Tolkien',      1937, 310, 4.3, 'Fantasy'),
  ('Fahrenheit 451',                        'Ray Bradbury',        1953, 158, 3.9, 'Dystopian'),
  ('Animal Farm',                           'George Orwell',       1945, 112, 3.9, 'Satire'),
  ('Lord of the Rings',                     'J.R.R. Tolkien',      1954, 1178, 4.5, 'Fantasy'),
  ('The Lord of the Rings II',              'J.R.R. Tolkien',      1954, 352, 4.5, 'Fantasy'),
  ('The Lord of the Rings III',             'J.R.R. Tolkien',      1955, 416, 4.5, 'Fantasy'),
  ('Crime and Punishment',                  'Fyodor Dostoevsky',   1866, 671, 4.2, 'Classic'),
  ('The Brothers Karamazov',                'Fyodor Dostoevsky',   1880, 796, 4.3, 'Classic'),
  ('Anna Karenina',                         'Leo Tolstoy',         1877, 864, 4.1, 'Classic'),
  ('War and Peace',                         'Leo Tolstoy',         1869, 1225, 4.1, 'Classic'),
  ('The Stranger',                          'Albert Camus',        1942, 123, 4.0, 'Philosophical'),
  ('The Trial',                             'Franz Kafka',         1925, 255, 3.9, 'Philosophical'),
  ('One Hundred Years of Solitude',         'Gabriel García Márquez', 1967, 417, 4.1, 'Magical Realism'),
  ('Love in the Time of Cholera',           'Gabriel García Márquez', 1985, 348, 4.0, 'Romance'),
  ('Beloved',                               'Toni Morrison',       1987, 324, 3.9, 'Historical'),
  ('Slaughterhouse-Five',                   'Kurt Vonnegut',       1969, 275, 4.1, 'Satire'),
  ('Catch-22',                              'Joseph Heller',       1961, 453, 4.0, 'Satire'),
  ('The Sun Also Rises',                    'Ernest Hemingway',    1926, 251, 3.8, 'Classic'),
  ('For Whom the Bell Tolls',               'Ernest Hemingway',    1940, 471, 4.0, 'Historical'),
  ('The Old Man and the Sea',               'Ernest Hemingway',    1952, 127, 3.8, 'Classic'),
  ('A Farewell to Arms',                    'Ernest Hemingway',    1929, 332, 3.9, 'Historical'),
  ('The Bell Jar',                          'Sylvia Plath',        1963, 244, 4.0, 'Classic'),
  ('Frankenstein',                          'Mary Shelley',        1818, 280, 3.8, 'Gothic'),
  ('Dracula',                               'Bram Stoker',         1897, 418, 4.0, 'Gothic'),
  ('Wuthering Heights',                     'Emily Brontë',        1847, 416, 3.9, 'Romance'),
  ('Jane Eyre',                             'Charlotte Brontë',    1847, 532, 4.1, 'Romance'),
  ('Great Expectations',                    'Charles Dickens',     1861, 505, 3.8, 'Classic'),
  ('A Tale of Two Cities',                  'Charles Dickens',     1859, 489, 4.0, 'Historical'),
  ('Oliver Twist',                          'Charles Dickens',     1839, 608, 3.9, 'Classic'),
  ('Moby-Dick',                             'Herman Melville',     1851, 635, 3.5, 'Classic'),
  ('The Adventures of Huckleberry Finn',    'Mark Twain',          1884, 366, 3.8, 'Classic'),
  ('The Adventures of Tom Sawyer',          'Mark Twain',          1876, 244, 3.9, 'Classic'),
  ('Of Mice and Men',                       'John Steinbeck',      1937, 107, 3.9, 'Classic'),
  ('The Grapes of Wrath',                   'John Steinbeck',      1939, 464, 4.0, 'Historical'),
  ('East of Eden',                          'John Steinbeck',      1952, 601, 4.4, 'Classic'),
  ('Dune',                                  'Frank Herbert',       1965, 688, 4.2, 'Sci-Fi'),
  ('Foundation',                            'Isaac Asimov',        1951, 244, 4.2, 'Sci-Fi'),
  ('Ender''s Game',                          'Orson Scott Card',    1985, 324, 4.3, 'Sci-Fi'),
  ('Hyperion',                              'Dan Simmons',         1989, 482, 4.2, 'Sci-Fi'),
  ('Snow Crash',                            'Neal Stephenson',     1992, 470, 4.0, 'Sci-Fi'),
  ('Neuromancer',                           'William Gibson',      1984, 271, 3.9, 'Sci-Fi'),
  ('A Game of Thrones',                     'George R.R. Martin',  1996, 694, 4.5, 'Fantasy'),
  ('The Name of the Wind',                  'Patrick Rothfuss',    2007, 662, 4.5, 'Fantasy'),
  ('The Way of Kings',                      'Brandon Sanderson',   2010, 1007, 4.7, 'Fantasy');
